/configver                                     2
/panels                                        1
/panels/dark-mode                              true
/panels/panel-0/autohide-behavior              0
/panels/panel-0/background-style               0
/panels/panel-0/enable-struts                  true
/panels/panel-0/icon-size                      0
/panels/panel-0/length                         100
/panels/panel-0/length-adjust                  true
/panels/panel-0/mode                           0
/panels/panel-0/plugin-ids                     [1,3,4,8,11,12]
/panels/panel-0/position                       p=8;x=400;y=583
/panels/panel-0/position-locked                true
/panels/panel-0/size                           24
/panels/panel-0/span-monitors                  false
/panels/panel-1/position                       p=8;x=0;y=300
/plugins/plugin-1                              whiskermenu
/plugins/plugin-11                             separator
/plugins/plugin-11/expand                      false
/plugins/plugin-11/style                       0
/plugins/plugin-12                             clock
/plugins/plugin-12/digital-format              %I:%M %p
/plugins/plugin-12/digital-layout              3
/plugins/plugin-12/digital-time-font           Helvetica 8
/plugins/plugin-12/digital-time-format         %I:%M %p
/plugins/plugin-12/timezone                    America/Cuiaba
/plugins/plugin-1/button-icon                  archlinux-logo
/plugins/plugin-1/button-title                 Start
/plugins/plugin-1/category-icon-size           0
/plugins/plugin-1/command-switchuser           dm-tool switch-to-greeter
/plugins/plugin-1/favorites                    [xfce4-web-browser.desktop,xfce4-mail-reader.desktop,xfce4-file-manager.desktop,xfce4-terminal-emulator.desktop]
/plugins/plugin-1/favorites-in-recent          true
/plugins/plugin-1/launcher-icon-size           1
/plugins/plugin-1/launcher-show-description    false
/plugins/plugin-1/menu-height                  383
/plugins/plugin-1/menu-width                   299
/plugins/plugin-1/position-commands-alternate  true
/plugins/plugin-1/position-search-alternate    true
/plugins/plugin-1/recent                       [xfce-settings-manager.desktop,xfce-ui-settings.desktop,xfce4-web-browser.desktop,org.xfce.mousepad.desktop,firefox.desktop,qalculate-gtk.desktop,spotify-launcher.desktop,vim.desktop,xfce-mouse-settings.desktop,floorp.desktop]
/plugins/plugin-1/show-button-title            true
/plugins/plugin-1/show-command-lockscreen      false
/plugins/plugin-1/show-command-logout          false
/plugins/plugin-1/show-command-logoutuser      true
/plugins/plugin-1/show-command-restart         false
/plugins/plugin-1/show-command-shutdown        true
/plugins/plugin-1/sort-categories              false
/plugins/plugin-1/view-mode                    2
/plugins/plugin-3                              tasklist
/plugins/plugin-3/flat-buttons                 false
/plugins/plugin-3/show-handle                  false
/plugins/plugin-3/show-labels                  true
/plugins/plugin-3/show-tooltips                true
/plugins/plugin-4                              separator
/plugins/plugin-4/expand                       true
/plugins/plugin-4/style                        0
/plugins/plugin-8                              showdesktop
