/Gdk/WindowScalingFactor        1
/Gtk/ButtonImages               true
/Gtk/CanChangeAccels            false
/Gtk/ColorPalette               black:white:gray50:red:purple:blue:light blue:green:yellow:orange:lavender:brown:goldenrod4:dodger blue:pink:light green:gray10:gray30:gray75:gray90
/Gtk/CursorThemeName            Chicago95 Standard Cursors
/Gtk/CursorThemeSize            0
/Gtk/DecorationLayout           icon,menu:minimize,maximize,close
/Gtk/DialogsUseHeader           false
/Gtk/FontName                   Helvetica Bold 8
/Gtk/IconSizes                  
/Gtk/KeyThemeName               
/Gtk/MenuBarAccel               F10
/Gtk/MenuImages                 true
/Gtk/MonospaceFontName          Monospace 10
/Gtk/TitlebarMiddleClick        lower
/Net/CursorBlink                true
/Net/CursorBlinkTime            1200
/Net/DndDragThreshold           8
/Net/DoubleClickDistance        5
/Net/DoubleClickTime            400
/Net/EnableEventSounds          true
/Net/EnableInputFeedbackSounds  true
/Net/FallbackIconTheme          Adwaita
/Net/IconThemeName              Chicago95-tux
/Net/SoundThemeName             Chicago95
/Net/ThemeName                  Chicago95-Dark
/Xfce/LastCustomDPI             85
/Xfce/SyncThemes                true
/Xft/Antialias                  1
/Xft/DPI                        -1
/Xft/Hinting                    -1
/Xft/HintStyle                  hintfull
/Xft/RGBA                       none
